name: shark_bait
description: Created to assist with Shark Bait groups during wrestling practice.
publish_to: 'none'
#learn : Shark Bait

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mailto: ^2.0.0
 # flutter_native_splash: ^2.4.2
  firebase_core: ^3.8.0
  vibration: ^2.0.1
  firebase_analytics: ^11.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


#flutter_native_splash:
 # color: "#B3B3B3"
 # image: assets/splash.png
  #branding: assets/dart.png
  #branding_mode: bottom
  #branding_bottom_padding:24

android_12:
  android_gravity: center

flutter:
  uses-material-design: true
